;
; File generated by cc65 v 2.16 - Git f5e9b40
;
	.fopt		compiler,"cc65 v 2.16 - Git f5e9b40"
	.setcpu		"6502"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	off
	.importzp	sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.import		_level0
	.export		_get_screen

; ---------------------------------------------------------------
; unsigned char __near__ __fastcall__ get_screen (unsigned char, unsigned char)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_get_screen: near

.segment	"CODE"

;
; uint8_t __fastcall__ get_screen(uint8_t scrn, uint8_t offset) {
;
    sta     ptr1
    jsr     popa
    sta     ptr1+1

	clc
	lda     #<(_level0)
	adc     ptr1
	sta     ptr1

	lda     #>(_level0)
	adc     ptr1+1
	sta     ptr1+1

    ldy     #0
    lda     (ptr1),y
    rts

; }
;

.endproc

